all:
	g++ -o image_recog image_recog.cpp `pkg-config --cflags --libs opencv`
	#g++ -o lastplay lastplay.cpp `pkg-config --cflags --libs opencv`
	#g++ -o avgcolor avgcolor.cpp `pkg-config --cflags --libs opencv`
	#g++ -o identify_countries identify_countries.cpp `pkg-config --cflags --libs opencv`
	#g++ -o searchimage searchimage.cpp `pkg-config --cflags --libs opencv`
